# Generated by Django 3.1.6 on 2021-08-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qfull_name', models.TextField(default='', max_length=120)),
                ('qbirthday', models.TextField(default='', max_length=10)),
                ('qage', models.IntegerField(default='')),
                ('qaddress', models.TextField(default='', max_length=20)),
                ('gstatus', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Work_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwork_experience', models.TextField(default='', max_length=20)),
                ('kskills', models.TextField(default='', max_length=30)),
                ('kseminars_att', models.TextField(default='', max_length=30)),
                ('kposition', models.TextField(default='', max_length=20)),
                ('kpromotions', models.TextField(default='', max_length=30)),
                ('khistory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMList.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='Educational_Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gprimary_level', models.TextField(default='', max_length=50)),
                ('gsecondary_level', models.TextField(default='', max_length=50)),
                ('gtertiary_level', models.TextField(default='', max_length=50)),
                ('personal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMList.personal_info')),
            ],
        ),
    ]
