# Generated by Django 3.1.6 on 2021-08-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpassed', models.TextField(default='', max_length=30)),
                ('wfailed', models.TextField(default='', max_length=30)),
                ('wresume', models.TextField(default='', max_length=30)),
                ('wcover_letter', models.TextField(default='', max_length=30)),
                ('wrecommendation', models.TextField(default='', max_length=30)),
                ('wtranscript', models.TextField(default='', max_length=30)),
                ('wportfolio', models.TextField(default='', max_length=30)),
                ('wcert', models.TextField(default='', max_length=30)),
                ('wphilhealth', models.TextField(default='', max_length=30)),
                ('wsss', models.TextField(default='', max_length=30)),
                ('wtemporary', models.TextField(default='', max_length=30)),
                ('wpermanent', models.TextField(default='', max_length=30)),
                ('wresign', models.TextField(default='', max_length=30)),
                ('wfired', models.TextField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qfull_name', models.TextField(default='', max_length=120)),
                ('qbirthday', models.TextField(default='', max_length=10)),
                ('qage', models.IntegerField(default='')),
                ('qaddress', models.TextField(default='', max_length=20)),
                ('gstatus', models.TextField(default='')),
                ('gprimary_level', models.TextField(default='', max_length=50)),
                ('gsecondary_level', models.TextField(default='', max_length=50)),
                ('gtertiary_level', models.TextField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wseminars', models.TextField(default='', max_length=30)),
                ('wskills', models.TextField(default='', max_length=30)),
                ('wexperince', models.TextField(default='', max_length=30)),
                ('wcompany', models.TextField(default='', max_length=30)),
                ('wposition', models.TextField(default='', max_length=30)),
                ('wpromotion', models.TextField(default='', max_length=30)),
                ('personal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMList.personalinfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='work_history',
            name='khistory',
        ),
        migrations.DeleteModel(
            name='Educational_Background',
        ),
        migrations.DeleteModel(
            name='Personal_Info',
        ),
        migrations.DeleteModel(
            name='Work_History',
        ),
    ]
