# Generated by Django 3.1.6 on 2021-08-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMList', '0002_auto_20210807_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhistory',
            old_name='personal',
            new_name='personalinfo',
        ),
    ]
