# Generated by Django 3.1.6 on 2021-08-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMList', '0003_auto_20210807_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='qemail',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='qnumber',
            field=models.TextField(default='', max_length=20),
        ),
    ]
