# Generated by Django 3.1.6 on 2021-08-09 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMList', '0004_auto_20210808_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='qemail',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='qnumber',
        ),
    ]
