# Generated by Django 3.1.6 on 2021-08-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMList', '0005_auto_20210809_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='qemail',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='qnumber',
            field=models.TextField(default='', max_length=20),
        ),
    ]
