# Generated by Django 3.1.6 on 2021-08-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMList', '0006_auto_20210809_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='wcert',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wcover_letter',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wfailed',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wfired',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wpassed',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wpermanent',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wphilhealth',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wportfolio',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wrecommendation',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wresign',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wresume',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wsss',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wtemporary',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wtranscript',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='gprimary_level',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='gsecondary_level',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='gtertiary_level',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='qbirthday',
        ),
        migrations.AddField(
            model_name='admin',
            name='apassword',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='admin',
            name='ausername',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='gfile',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='upassword',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='uusername',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='qaddress',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Workhistory',
        ),
    ]
